### ISSUE TITLE
LEN-B-1: Application crashes when Librus displays a modal window with a survey

### ISSUE THREAD

**Issue by SebastianCelejewski** [SebastianCelejewski/librus-email-notifications#1]
/home/ec2-user/.gem/ruby/2.0/gems/poltergeist-1.7.0/lib/capybara/poltergeist/node.rb:23:in `rescue in command': Firing a click at co-ordinates [580.5, 361] faed. Poltergeist detected another element with CSS selector 'html body div#centrumPowiadomien.modal-box div.warning-box.information.moveable.medium' at this potion. It may be overlapping the element you are trying to interact with. If you don't care about overlapping elements, try using node.trigger('click'). (Capyba::Poltergeist::MouseEventFailed)
        from /home/ec2-user/.gem/ruby/2.0/gems/poltergeist-1.7.0/lib/capybara/poltergeist/node.rb:17:in`command'
        from /home/ec2-user/.gem/ruby/2.0/gems/poltergeist-1.7.0/lib/capybara/poltergeist/node.rb:116:in `click'
        from /home/ec2-user/.gem/ruby/2.0/gems/capybara-2.5.0/lib/capybara/node/element.rb:134:in`block in click'
        from /home/ec2-user/.gem/ruby/2.0/gems/capybara-2.5.0/lib/capybara/node/base.rb:84:in `synchronize'
        from /home/ec2-user/.gem/ruby/2.0/gems/capybara-2.5.0/lib/capybara/node/element.rb:134:in`click'
        from /home/ec2-user/librus/librus-email-notifications/lib/messages_parser.rb:42:in `block in process'
        from /home/ec2-user/librus/librus-email-notifications/lib/messages_parser.rb:36:in`each'
        from /home/ec2-user/librus/librus-email-notifications/lib/messages_parser.rb:36:in `process'
        from bin/librus_email_notifications.rb:67:in`module:LibrusEmailNotifications'
        from bin/librus_email_notifications.rb:3:in `<main>'

**Comment by SebastianCelejewski** [comment]
Fixed by 5c448fc507672d525619bdf51ccd6b8b5c0ce33a
